name: Angular Build

# {1}
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  angular:
    name: Angular Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        # https://angular.dev/reference/versions
    steps:
 
      - name: Checkout the source code
        uses: actions/checkout@v3

      # {3}
      - name: Setup Node.js 22
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci
   
      - name: Run tests
        run: npm run test:ci

      - name: Build
        run: npm run build
